### PR TITLE
Add support for Chamberlain openers with embedded MyQ

### PR DESCRIPTION
**Pull request by harpchad**
Added an additional match in the device iteration loop to support Chamberlain openers with built in MyQ.

### CODE REVIEW

**Comment by AppleTechy** [comment]
I was wondering if you got this exact index.js to work? I am currently recieving the error Error 'null' logging in: {"ReturnCode":"217","ErrorMessage":"Error processing request (217)","CorrelationId":"47d7358b-36a2-419d-aa49-8842ae894ed6"}. Any help would be appreciated.
Thanks, AppleTechy

**Comment by harpchad** [comment]
In my case it couldn't find my opener because the MyQDeviceTypeName didn't match what the plugin was looking for.  I didn't get an error.  I suspect the 217 error is passed back from the myQ, does the myQ mobile app work?

**Comment by AppleTechy** [comment]
Yes, the MyQ can successfully operate my garage doors. Home Bridge doesn't even pickup my garage door the only message it says is "Garage door Initializing" . When I then go in to my HomeKit app to try and force it to pick up my garage door. It then gives me the error. I can give you the full error if you need it. I have been in contact with nfarina about trying to get this fix and neither of use could find a solution yesterday. 
Thanks, Apple G.

**Comment by jw59** [comment]
The change in this PR works for my Chamberlain device w/ MyQ embedded.

**Comment by nfarina** [comment]
This is great, thanks!

**Pull request merged**
